export const TIME_DELAY_ROUTING = 100;
export const LINE_LAYOUT_EFFECT = 5;
export const TIME_WAIT_LOADED_TRIGGER = 500;
export const TIME_WAIT_PAGE_ENTER_TRANSITION = 500;
export const TIMEOUT_UNREGISTER_ASSETS = 150;

export const CACHE_IMAGES_PRELOADER = 'CACHE_IMAGES_PRELOADER';
