export const TIME_DELAY_ROUTING = 100;
export const LINE_LAYOUT_EFFECT = 5;
export const TIME_WAIT_LOADED_TRIGGER = 300;
export const TIME_WAIT_PAGE_ENTER_TRANSITION = 300;
export const TIMEOUT_UNREGISTER_ASSETS = 100;

export const BREAKPOINT_MOBILE = 768;
export const BREAKPOINT_TABLET = 1200;

export const TIME_DELAY_RESIZE = 150;
